// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adcotdlglpalcauodxsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkY290ZGxnbHBhbGNhdW9keHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzUwNjEsImV4cCI6MjA3MzUxMTA2MX0.dNxIutY9T_xGAK6J4DxSVj_mDjTYwfOITAOM3Opav-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});